// <auto-generated />
using System;
using LoadBalancer.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoadBalancer.WebApi.Migrations
{
    [DbContext(typeof(LoadBalancerDbContext))]
    partial class LoadBalancerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoadBalancer.WebApi.Data.Entities.PuzzleEntity.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dimension")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("TimeResult")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("LoadBalancer.WebApi.Data.Entities.StateEntity.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("LoadBalancer.WebApi.Data.Entities.UzerToPuzzleEntity.UzerToPuzzle", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxCount")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserToPuzzle");
                });

            modelBuilder.Entity("LoadBalancer.WebApi.Data.Entities.PuzzleEntity.Puzzle", b =>
                {
                    b.HasOne("LoadBalancer.WebApi.Data.Entities.StateEntity.State", "State")
                        .WithMany("Puzzles")
                        .HasForeignKey("StateId");

                    b.HasOne("LoadBalancer.WebApi.Data.Entities.UzerToPuzzleEntity.UzerToPuzzle", "UserToPuzzle")
                        .WithMany("Puzzles")
                        .HasForeignKey("UserId");

                    b.Navigation("State");

                    b.Navigation("UserToPuzzle");
                });

            modelBuilder.Entity("LoadBalancer.WebApi.Data.Entities.StateEntity.State", b =>
                {
                    b.Navigation("Puzzles");
                });

            modelBuilder.Entity("LoadBalancer.WebApi.Data.Entities.UzerToPuzzleEntity.UzerToPuzzle", b =>
                {
                    b.Navigation("Puzzles");
                });
#pragma warning restore 612, 618
        }
    }
}
